config/routes.rb
OnlineStore::Application.routes.draw do
  get "users/new"
  get "users/create"
  resources :products do
    resources :reviews, :except => [:index]
  end
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  root 'products#index'

end

app/models/categories_products.rb
class CategoriesProducts < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, :through => :reviews
  has_and_belongs_to_many :categories

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates :comment, :presence =>true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :products, :through => :reviews

  validates_presence_of :name
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if  session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @category = 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :load_product, :only => [:edit, :show, :update]

  def index
    @products = if params[:search]
      Product.where("name LIKE ?", "%#{params[:search]}%")
     else
       Product.all
     end

    @products = @products.page(params[:page]).order("created_at DESC");

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def show
    if current_user
      @review = @product.reviews.new
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def update

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

  def load_product
    @product = Product.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, only: [:show]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html {redirect_to products_path, notice: 'Review created successfully'}
        format.js 
      else
        format.html { render :action => :show }
        format.js 
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_path, :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_path, :notice => "Signed Up!"
    else
      render "new"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineStore</title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script > </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notict] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end%>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %> 
  
  <%= yield %>
    
    <p class="userinfo">
    <% if current_user %>
      Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path %> or <%= link_to "Sign Up", new_user_path %>
    <% end %>
    </p>
   
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved: </h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end%>
      </ul>
    </div>
  <% end %>



  <div class='field'>
    <%= f.label :name %> <br />
    <%= f.text_field :name %> 
  </div>
   <div class='field'>
    <%= f.label :description %> <br />
    <%= f.text_area :description %>
  </div>
   <div class='field'>
    <%= f.label :price_in_cents %> <br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
  <br /> ------------------------<br/>
  <%=  product[:name] %>
  <%= link_to "view", product_path(product.id) %>
  <br>
  <%= product[:description] %> <br />
  <%= product.formatted_price %><br />
  Comments:<%= product.reviews.count %> <br />
  <br />
 

app/views/products/_review_form_errors.html.erb
  <% if @review.errors.present? %>
    <% @review.errors.full_message.each do |error| %>
      <div class="alert">
        <%= error %>
      </div>
    <% end %>
  <% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <p>
  ------------------<br/>
  Comment: <%= review.comment %>
  <br />
  <%if review.user != nil %>
    <em> by <%= review.user.name  %></em><br />
    Added on: <%= review.created_at %>
  <% end %>

  </p> 
<% end %>

app/views/products/edit.html.erb
<h1>Edit this product</h1>

<%= render "form" %>

<%= link_to "Back", products_path %> 

app/views/products/index.html.erb
<h1>Products</h1>
<%= link_to "New", new_product_path %>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search], id:"search" %>
  <%= submit_tag "Search" %>
<% end %>

<div id="products">
  <%= render @products %>
</div>


<%= paginate @products %>

app/views/products/index.js.erb
<% if params[:search]  %>
  $('#products').html("<%= j(render @products) %>");
<% else %>
  $('#products').append('<%= j(render(@products)) %>');
$('.pagination').replaceWith('<%= j(paginate(@products)) %>');
<% end %>

app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= render "form" %>

<%= link_to "Back", products_path %> 

app/views/products/show.html.erb
<h1><%= @product[:name] %></h1>

Price: <%= @product.formatted_price %>
<p>
<%= @product[:description] %> <br/>

</p>


<h3>Reviews for <%= @product.name %></h3>

<div id="review-list">
  <%= render :partial => "reviews" %>
</div>

<%= link_to "Back", products_path %> | 
<%= link_to "Edit", edit_product_path(@product) %>   <br />
<br />
<br />
<%= button_to "Delete", @product, method: :delete, :class => :destroy %>

<% if current_user %>

  <h4>New Review</h4>


  <div id="new_review">
    <%= form_for [@product, @review], :remote => true  do |f| %>
      <% if @review.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
          <ul>
            <% @review.errors.full_message.each do |msg| %>
              <li><%= msg %></li>
            <% end%>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :comment %><br />
        <%= f.text_area :comment %>
      </div> 
      <div class="actions">
        <%= f.submit %><br />
      </div> 
    <% end %>
  </div>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

<script type="text/javascript">
  $(function() {
      $("#new_review")
      .on('ajax:beforeSend', function() {
        $("input[type='submit']")
        .val('Saving...')
        .attr('disabled','disabled');
        })
      .on('ajax:complete', function(){
        $("input[type='submit']")
        .val('Create Review')
        .removeAttr('disabled');
        });
      });
    </script>

app/views/products/show.js.erb
$('body').append("<%= escape_javascript(render @product) %>");

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
$("#review_comment").val('');
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_message">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :email %> <br />
    <%= f.text_field :email %> <br/>
  </div>
  <div class="field">
    <%= f.label :name %> <br />
    <%= f.text_field :name %> <br/>
  </div>

  <div class="field">
    <%= f.label :password %> <br />
    <%= f.password_field :password %> <br/>
  </div>
 
  <div class="field">
    <%= f.label :password_confirmation %> <br />
    <%= f.password_field :password_confirmation %> <br/>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>